--新增職稱代碼表(Position)
CREATE TABLE [dbo].[Position](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Position] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


---------------------------------------------------
SET IDENTITY_INSERT [dbo].[Position] ON 

INSERT [dbo].[Position] ([Id], [Name]) VALUES (1, N'助理環境技術師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (2, N'技士')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (3, N'科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (4, N'科員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (5, N'約聘人員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (6, N'特約助理')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (7, N'秘書')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (8, N'高級環境工程師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (9, N'副處長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (10, N'組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (11, N'處長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (12, N'環境技術師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (13, N'簡任技正')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (16, N'薦任技士')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (17, N'薦任技正')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (18, N'薦任科員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (19, N'技正')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (20, N'隊員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (22, N'隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (23, N'分隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (24, N'技佐')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (25, N'技工')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (26, N'約僱稽查員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (27, N'副大隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (28, N'局長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (29, N'暫存')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (30, N'助理員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (31, N'大隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (32, N'專門委員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (33, N'主任')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (34, N'執行秘書')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (35, N'副執行秘書')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (36, N'總隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (37, N'副總隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (38, N'技監')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (39, N'簡研')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (40, N'助研')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (41, N'副局長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (42, N'督察員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (43, N'中隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (44, N'副中隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (45, N'約用人員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (46, N'資訊顧問')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (47, N'稽查員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (48, N'主任秘書')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (49, N'專員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (50, N'約用助環')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (51, N'約僱人員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (52, N'股長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (53, N'特約管理師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (54, N'副研')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (55, N'聘用環境技術師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (56, N'簡任人員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (57, N'約用')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (58, N'約僱技士')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (59, N'衛生稽查員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (60, N'場長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (61, N'助理管理師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (62, N'助理毒管師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (63, N'視察')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (64, N'辦事員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (65, N'警務員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (66, N'承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (67, N'廠長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (68, N'班長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (69, N'副廠長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (70, N'副總經理')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (71, N'協理')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (72, N'技術長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (73, N'課長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (74, N'區隊長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (75, N'臨時約僱人員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (76, N'環境管理師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (77, N'書記')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (78, N'稽核員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (79, N'簡任視察')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (80, N'財務管理師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (81, N'特約助理管理師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (82, N'第2組組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (83, N'回收業(北區)承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (84, N'回收業(南區)承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (85, N'處理業承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (86, N'第3組副組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (87, N'非塑膠容器承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (88, N'廢塑膠容器承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (89, N'第4組組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (90, N'第5組組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (91, N'廢輪胎承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (92, N'廢乾電池承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (93, N'廢照明光源承辦人')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (94, N'祕書')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (95, N'薦任技佐')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (96, N'管理師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (97, N'助理工程師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (98, N'專案')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (99, N'聘用稽查員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (100, N'環境監測')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (101, N'所長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (102, N'廢鉛蓄電池承辦人')
GO
INSERT [dbo].[Position] ([Id], [Name]) VALUES (103, N'分析師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (104, N'司長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (105, N'副司長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (106, N'署長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (107, N'副署長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (108, N'科(課)長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (109, N'組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (110, N'副組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (111, N'綜合規劃組組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (112, N'綜合規劃組副組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (113, N'綜合規劃組土水整治發展科科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (114, N'綜合規劃組土水整治發展科承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (115, N'環境衛生組組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (116, N'環境衛生組副組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (117, N'環境衛生組災害應變科科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (118, N'環境衛生組災害應變科承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (119, N'環境衛生組環衛管理科科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (120, N'環境衛生組環衛管理科承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (121, N'一般廢棄物管理組組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (122, N'一般廢棄物管理組副組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (123, N'一般廢棄物管理組簡任技正')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (124, N'一般廢棄物管理組前處理營運管理科科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (125, N'一般廢棄物管理組前處理營運管理科承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (126, N'一般廢棄物管理組中間及最終處置管理科科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (127, N'一般廢棄物管理組中間及最終處置管理科承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (128, N'一般廢棄物管理組設施調度及廚餘處理科科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (129, N'一般廢棄物管理組設施調度及廚餘處理科承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (130, N'一般廢棄物管理組科技研發及應用科科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (131, N'一般廢棄物管理組科技研發及應用科承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (132, N'北區環境管理中心主任')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (133, N'北區環境管理中心副主任')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (134, N'北區環境管理中心簡任技正')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (135, N'北區環境管理中心科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (136, N'北區環境管理中心承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (137, N'中區環境管理中心主任')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (138, N'中區環境管理中心副主任')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (139, N'中區環境管理中心簡任技正')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (140, N'中區環境管理中心科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (141, N'中區環境管理中心承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (142, N'南區環境管理中心主任')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (143, N'南區環境管理中心副主任')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (144, N'南區環境管理中心簡任技正')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (145, N'南區環境管理中心科長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (146, N'南區環境管理中心承辦')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (147, N'土壤及地下水污染整治基金管理會副執行秘書')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (148, N'土壤及地下水污染整治基金管理會風險管理分組分組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (149, N'土壤及地下水污染整治基金管理會風險管理分組副分組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (150, N'土壤及地下水污染整治基金管理會風險管理分組環境技術師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (151, N'約僱技佐')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (152, N'特約環境技術師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (153, N'特約助理環境技術師')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (154, N'分組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (155, N'副分組長')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (156, N'組員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (157, N'工程員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (158, N'聘用研究員')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (159, N'環境衛生組簡任技正　　')
INSERT [dbo].[Position] ([Id], [Name]) VALUES (160, N'代理科長')
SET IDENTITY_INSERT [dbo].[Position] OFF
GO
